### ISSUE TITLE
router

### ISSUE THREAD

**Issue by patychavezromo** [AndyApG/DEV009-social-network#2]
https://www.youtube.com/watch?v=vFh18oo2Cu4&ab_channel=Dev-Labo

**Comment by AndyApG** [comment]
1.  https://developer.mozilla.org/es/docs/Web/API/History/pushState
2.  https://developer.mozilla.org/es/docs/Web/API/Location/origin
3. https://developer.mozilla.org/en-US/docs/Web/API/Location/pathname
4. https://desarrolloweb.com/articulos/funciones-recursivas-recursividad.html
5. https://developer.mozilla.org/es/docs/Web/API/Window/popstate_event
6. https://developer.mozilla.org/en-US/docs/Web/API/Node/firstChild
