### ISSUE TITLE
HU 3: Visualizar muro/timeline con Publicaciones

### ISSUE THREAD

**Issue by patychavezromo** [AndyApG/DEV009-social-network#39]
**YO** como usaria, **DESEO** ver el contenido que me interesa publicado en el feed de la plataforma **PARA** nutrirme de nuevos conocimientos respecto a maternidad.

**Criterios de Aceptación**

- [x] Verificar si el usuario está logueado antes de mostrar contenido

- [x] Mensaje de Bienvenida 
- [x] Ver contenido en el muro (muestra las publicaciones más recientes y relevantes de la comunidad). 
- [ ]Diseño organizado y fácil de leer, donde cada publicación debe incluir el nombre del autor, la fecha y hora de la publicación, 
      y  el contenido compartido.
* contenido de etiquetas de intereses
- [x]  limite de caracteres 300
- [x]  Debe existir una caja de texto y un botón claramente visible que me permita acceder a la función de "Publicar"
- [x] Solo puedo publicar comentarios con información, nunca mensajes vacíos.

_**Definición de terminado**_

* Da una experiencia de usuario intuitiva.
* Cumple con los criterios de aceptación
* Debe ser una SPA
* Es responsive
* Pasan los test unitarios
* Recibimos code review de al menos una compañera de otro equipo.
* La documentación se encuentra actualizada en el readme.
* Se realizan pruebas manuales buscando errores e imperfecciones simples.
* Se implementa todo el feedback que recibimos.
* Despliegue de aplicación y etiquetaron la versión (git tag).

**Comment by patychavezromo** [comment]
- [ ] hacer una función para leer los datos de realtimedatabase y poder mostrar el nombre del usuario con el mensaje de bienvenida.
- [ ] hacer las configuraciones con grid para dividir la página y dar proporciones al espacio del

**Comment by patychavezromo** [comment]
[archivo de prueba timeLine](https://gist.github.com/patychavezromo/b61fee8019b2d0d3c396dcd9483cf5c6)

**Comment by AndyApG** [comment]
recuperar datos

https://gist.github.com/AndyApG/e286cc038eab725b59cf5fda20a080f8
